name: PR

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: install
        run: yarn

      - name: build
        run: yarn build

      - name: lint
        run: yarn lint
