name: PR

on: [pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install dependencies
        run: yarn

      - name: Build the project
        run: yarn build

  check_linting:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Check Linting
        run: yarn lint
