name: PR

on: [pull_request]

jobs:
  pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install dependencies
        run: yarn

      - name: Build the project
        run: yarn build

      - name: Check Linting
        run: yarn lint
